#!/bin/bash

if [[ "bj" == $MYPLATFORM ]]; do
  mkdir -p $THISDIR/$MYPLATFORM/$MYNAME
  cp $MYDIRNAME/$MYNAME.cpp $THISDIR/$MYPLATFORM/$MYNAME/$MYNAME.cpp
else
  mkdir -p $THISDIR/$MYPLATFORM/$MYSET/$MYNAME
  cp $MYDIRNAME/$MYNAME.cpp $THISDIR/$MYPLATFORM/$MYSET/$MYNAME/$MYNAME.cpp
done
